### ISSUE TITLE
Persist State to Remote Backend

### ISSUE THREAD

**Issue by MeNsaaH** [MeNsaaH/reka#4]
Currently state files are stored locally. Reka should allow setting backend to remote sources such as s3 buckets, or google cloud storage. This will be useful in CI environments where reka will be executed

**Comment by deven96** [comment]
Would this be set via the config yaml?

**Comment by MeNsaaH** [comment]
Yes. Say

```yaml
StateBackend:
  type: s3
  bucket: bucket_name
  path: /path/to/local/store/state
```
